name: nqs_devel_gpu
channels:
  - pytorch
  - twesterhout
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - pynvim # Python support for Neovim
    - py-spy # For performance analysis
    - black # For formatting code
    - loguru # Logging
  - pytorch=1.9.1
  - cudatoolkit=10.2
  - numpy>=1.19
  - pyyaml
  - h5py
  # Stuff to compile extensions
  - gcc_linux-64
  - gxx_linux-64
  - ninja
  # Tools for generating Conda packages
  - anaconda-client
  - conda-build
  - conda-verify
  # Our own packages
  - lattice-symmetries
  - unpack-bits
