name: nqs_devel_cpu
channels:
  - twesterhout
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - black # For formatting code
  # Dependencies for Python code
  - lattice-symmetries
  - cpuonly
  - pytorch=1.8.1
  - numpy
  - scipy
  - h5py
  - pyyaml
  - tensorboard
  - pip:
    - loguru
    - pynvim # Python support for Neovim
    - py-spy # For performance analysis
  # For running experiments
  - pyyaml
  - h5py
  # Stuff to compile the package locally
  - gcc_linux-64
  - gxx_linux-64
  - cmake
  - ninja
