{% set data = load_setup_py_data() %}

package:
  name: nqs-playground
  version: {{ data.get('version') }}

source:
  # git_url: https://github.com/twesterhout/nqs-playground
  # git_rev: develop
  path: ../../
 
build:
  string: py{{ python }}_cuda{{ cudatoolkit }}_torch{{ pytorch }}_ls{{ ls }}
  stript_env:
    - TMPDIR

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{ python }}
    - cmake
    - ninja
    - _pytorch_select ==0.2
    - cudatoolkit {{ cudatoolkit }}
    - pytorch {{ pytorch }}
    - lattice-symmetries {{ ls }}

  run:
    - python
    - numpy x.x
    - scipy
    - psutil
    - loguru
    - tensorboard >=2.0
    - _pytorch_select ==0.2
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - {{ pin_compatible('pytorch', min_pin='x.x.x', max_pin='x.x.x') }}
    - {{ pin_compatible('lattice-symmetries', min_pin='x.x.x', max_pin='x.x.x') }}
