{% set data = load_setup_py_data() %}

package:
  name: nqs-playground
  version: {{ data.get('version') }}

source:
  path: ../../
 
build:
  string: py{{ python }}_cuda{{ cudatoolkit }}_torch{{ torch }}_ls{{ ls }}_1
  ignore_run_exports:
    - cudnn

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{ python }}
    - cmake
    - ninja
    - cudatoolkit {{ cudatoolkit }}
    - pytorch {{ torch }}
    - cudnn >=7.6.0,<8.1.0
    - lattice-symmetries {{ ls }}

  run:
    - _openmp_mutex
    - python
    - numpy
    - scipy
    - psutil
    - loguru
    - tensorboard >=2.0
    - cudatoolkit
    - {{ pin_compatible('pytorch', min_pin='x.x.x', max_pin='x.x.x') }}
    - lattice-symmetries
